### ISSUE TITLE
Difference between SGenDesktopLinux and SGen-Desktop

### ISSUE THREAD

**Issue by TechnologyClassroom** [connervieira/SGen-Libre#1]
The name was confusing to me.  It sounds like the name of a GNU/Linux distribution for desktops, but it is a program.

I would think this code could be merged with https://github.com/connervieira/SGen-Desktop

**Comment by connervieira** [comment]
I hadn't even considered that. The reason I currently have them as separate programs is because SGen Desktop on Mac uses Apple's proprietary libraries, and can't be ported over to GNU/Linux directly. I decided to restart and try to recreate the functionality of SGen Desktop from Mac on GNU/Linux using all free software.

Here are the options I'm considering to clear up the confusion:
1. Merge both into "SGen Desktop", and separate each OS's version by placing them into a "GNU Linux" and "MacOS" folder respectively.
2. Rename the SGen Desktop Linux to something more direct, like "SGen Desktop GNU/Linux version", or something along those lines.
3. Re-brand SGen Desktop Linux to something new entirely, like "SGen Libre".

I'm leaning towards the third option, as I think it would make the distinction between the GNU/Linux and Mac versions clear, but I'd love to hear what you think about it before implementing it.

**Comment by TechnologyClassroom** [comment]
I vote for SGen-Libre.  That is a common naming convention for a port that uses all free software such as the [Linux-libre kernel](https://en.wikipedia.org/wiki/Linux-libre).  Probably the easiest change to make of the lot as well.
